# Generated by Django 2.0.8 on 2018-10-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20180929_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='time_passed',
            field=models.DurationField(default=0),
        ),
    ]
