# Generated by Django 2.0.8 on 2018-10-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_notification_time_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='time_passed',
        ),
    ]
