# Generated by Django 2.0.8 on 2018-10-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_passed',
            field=models.DurationField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='time_passed',
            field=models.DurationField(default=0),
        ),
        migrations.AddField(
            model_name='like',
            name='time_passed',
            field=models.DurationField(default=0),
        ),
    ]
