# Generated by Django 2.0.8 on 2018-10-13 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20181013_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time_passed',
        ),
        migrations.RemoveField(
            model_name='image',
            name='time_passed',
        ),
        migrations.RemoveField(
            model_name='like',
            name='time_passed',
        ),
    ]
