# Generated by Django 2.0.8 on 2018-10-13 00:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20181013_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='durationtime',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
