# Generated by Django 2.0.8 on 2018-11-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20181013_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created',
        ),
    ]
