# Generated by Django 2.0.8 on 2018-09-25 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.ManyToManyField(blank=True, related_name='_user_subscribe_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='_user_subscribers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
